import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { run, Simulation } from '../simulator/sim'
import { SimulationStats } from '../components/IterationStats'

export default function Home() {
  const [numTargets, setNumTargets] = useState(1)
  const [duration, setDuration] = useState(60)
  const [sims, setSims] = useState<Simulation[] | null>(null)

  const onSimulate = () => {
    const sims = run({ numTargets, duration, iterationCount: 100 })
    setSims(sims)
  }

  return (
    <div className="px-8">
      <Head>
        <title>Mistweaver Sim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-8 flex flex-col gap-4">
        <h1 className={styles.title}>Mistweaver Sim</h1>
        <div className="flex flex-col gap-4">
          <div className="flex gap-2">
            <span>Targets</span>
            <input
              onChange={(e) => setNumTargets(Number(e.target.value))}
              value={numTargets}
            />
          </div>
          <div className="flex gap-2">
            Duration
            <input
              onChange={(e) => setDuration(Number(e.target.value))}
              value={duration}
            />
          </div>
          <button
            className="rounded-full px-4 py-1 bg-cyan-500 hover:bg-cyan-700"
            onClick={onSimulate}
          >
            Simulate!
          </button>
        </div>

        {sims && (
          <div className="flex flex-col gap-4">
            {sims.map((sim, idx) => {
              return (
                <SimulationStats
                  key={sim.nameWithTalents()}
                  index={idx}
                  sim={sim}
                />
              )
            })}
          </div>
        )}
      </main>
    </div>
  )
}
