import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { simulate } from '../simulator/sim'
import { SimulationStats } from '../components/SimulationStats'
import { Simulation } from '../simulator/simulator'
import { CharacterStats } from '../simulator/state'
import { Talent, talentNames } from '../simulator/talents'
import { NumericInput } from '../components/NumericInput'
import { Strategy, bestStrategies } from '../simulator/strategies'
import { CharacterStatsForm } from '../components/CharacterStatsForm'
import { StrategySelect } from '../components/StrategySelect'

const defaultCharacterStats: CharacterStats = {
  versatility: 0.1,
  haste: 0.1202,
  criticalStrike: 0.1508,
  attackPower: 6924,
  spellPower: 6658,
  weaponDps: 1593.47,
}

export const talentsToTest: Talent[] = [
  talentNames.secret_infusion,
  talentNames.secret_infusion_2,
  talentNames.invokers_delight,
  talentNames.focused_thunder,
  talentNames.bonedust_brew,
  talentNames.attenuation,
]

export default function Home() {
  const [duration, setDuration] = useState(60)
  const [numTargets, setNumTargets] = useState(1)
  const [iterations, setIterations] = useState(100)
  const [strategy, setStrategy] = useState<Strategy>(bestStrategies[1])
  const [characterStats, setCharacterStats] = useState(defaultCharacterStats)
  const [sims, setSims] = useState<Simulation[] | null>(null)

  const onSimulate = () => {
    const sims = simulate({
      characterStats,
      talentsToTest,
      strategy,
      numTargets,
      duration,
      iterations,
    })
    setSims(sims)
  }

  const onChangeTargets = (targets: number) => {
    setStrategy(bestStrategies[targets])
    setNumTargets(targets)
  }

  return (
    <div className="px-8">
      <Head>
        <title>Mistweaver Sim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-8 flex flex-col gap-4">
        <h1 className={styles.title}>Mistweaver Sim</h1>
        <div className="flex flex-col gap-4">
          <div className="flex gap-4">
            <NumericInput
              label="Duration"
              value={duration}
              onChange={setDuration}
              min={30}
              max={300}
            />
            <NumericInput
              label="Targets"
              value={numTargets}
              onChange={onChangeTargets}
              min={1}
              max={5}
            />
            <NumericInput
              label="Iterations"
              value={iterations}
              onChange={setIterations}
              min={1}
              max={10_000}
            />
          </div>
          <CharacterStatsForm
            characterStats={characterStats}
            onChange={setCharacterStats}
          />
          <StrategySelect selectedStrategy={strategy} onChange={setStrategy} />
          <button
            className="rounded-full px-4 py-1 bg-teal-500 hover:bg-teal-700 w-64 font-bold"
            onClick={onSimulate}
          >
            Simulate!
          </button>
        </div>

        {sims && (
          <div className="flex flex-col gap-4">
            {sims.map((sim, idx) => {
              return (
                <SimulationStats
                  key={sim.nameWithTalents(talentsToTest)}
                  index={idx}
                  sim={sim}
                  talentsToTest={talentsToTest}
                />
              )
            })}
          </div>
        )}
      </main>
    </div>
  )
}
